### ISSUE TITLE
Unrecognized index name wikipedia-dpr-100w

### ISSUE THREAD

**Issue by 2282588541a** [ignorejjj/MetaRAG#1]
I try run this code in my local environment, but when run the code like`from pyserini.search.lucene import LuceneSearcher
searcher = LuceneSearcher.from_prebuilt_index('wikipedia-dpr-100w')` The result show Unrecognized index name wikipedia-dpr-100w. I want to know how I can slove this

**Comment by ignorejjj** [comment]
See this: https://github.com/castorini/pyserini/blob/master/pyserini/resources/index-metadata/index-wikipedia-dpr-20210120-d1b9e6-readme.txt

**Comment by 2282588541a** [comment]
emm，I have try this ,It looks like I have to use `anserini `to generate index. When I apply anserini ,there are too many problems(the meaven show many errrors and I can't solve them), If conditions permit, can you upload the index you built? Aliyun, Google Drive. Thank you very much. Or will it have a big impact on the results if I replace the search part with other BM25-based search engines (similar to elastic)?

**Comment by ignorejjj** [comment]
You can download it from pyserini: https://github.com/castorini/pyserini/blob/master/docs/usage-interactive-search.md#how-do-i-manually-download-indexes

**Comment by 2282588541a** [comment]
thank you very much！！！Anyone can download this corpus in this link:`https://git.uwaterloo.ca/jimmylin/anserini-indexes/raw/master/index-wikipedia-dpr-20210120-d1b9e6.tar.gz`
